//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.16 at 06:26:47 PM NOVT 
//


package ru.trendtech.integration.payonline.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.trendtech.integration.payonline.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.trendtech.integration.payonline.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PayOnlineRequest }
     * 
     */
    public PayOnlineRequest createOPERATION() {
        return new PayOnlineRequest();
    }

    /**
     * Create an instance of {@link PayOnlineRequest.REMOTEINFO }
     * 
     */
    public PayOnlineRequest.REMOTEINFO createOPERATIONREMOTEINFO() {
        return new PayOnlineRequest.REMOTEINFO();
    }

    /**
     * Create an instance of {@link PayOnlineRequest.TARGET }
     * 
     */
    public PayOnlineRequest.TARGET createOPERATIONTARGET() {
        return new PayOnlineRequest.TARGET();
    }

    /**
     * Create an instance of {@link PayOnlineRequest.REMOTEINFO.ITEM }
     * 
     */
    public PayOnlineRequest.REMOTEINFO.ITEM createOPERATIONREMOTEINFOITEM() {
        return new PayOnlineRequest.REMOTEINFO.ITEM();
    }

    /**
     * Create an instance of {@link PayOnlineRequest.TARGET.KEYATTR }
     * 
     */
    public PayOnlineRequest.TARGET.KEYATTR createOPERATIONTARGETKEYATTR() {
        return new PayOnlineRequest.TARGET.KEYATTR();
    }

}
