//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.16 at 06:26:47 PM NOVT 
//


package ru.trendtech.integration.payonline.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oper_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="oper_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="start"/>
 *     &lt;enumeration value="commit"/>
 *     &lt;enumeration value="execute"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "oper_type")
@XmlEnum
public enum OperType {

    @XmlEnumValue("start")
    START("start"),
    @XmlEnumValue("commit")
    COMMIT("commit"),
    @XmlEnumValue("execute")
    EXECUTE("execute");
    private final String value;

    OperType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OperType fromValue(String v) {
        for (OperType c: OperType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
