//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.16 at 06:32:47 PM NOVT 
//


package ru.trendtech.integration.payonline.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oper_status.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="oper_status">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="new"/>
 *     &lt;enumeration value="accepted"/>
 *     &lt;enumeration value="committed"/>
 *     &lt;enumeration value="rejected"/>
 *     &lt;enumeration value="canceled"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "oper_status")
@XmlEnum
public enum OperStatus {

    @XmlEnumValue("new")
    NEW("new"),
    @XmlEnumValue("accepted")
    ACCEPTED("accepted"),
    @XmlEnumValue("committed")
    COMMITTED("committed"),
    @XmlEnumValue("rejected")
    REJECTED("rejected"),
    @XmlEnumValue("canceled")
    CANCELED("canceled");
    private final String value;

    OperStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OperStatus fromValue(String v) {
        for (OperStatus c: OperStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
